### ISSUE TITLE
Arrow keys not work

### ISSUE THREAD

**Issue by pomutemu** [zsh-users/zaw#56] opened 2015-01-02 07:59 UTC
[![Gyazo](http://i.gyazo.com/e43590c69e2a48e309e94ff3c286af67.png)](http://gyazo.com/e43590c69e2a48e309e94ff3c286af67)
Ctrl+b/f/n/p work fine.
All arrow keys work fine in zsh command line.

**Comment by termoshtt** [comment] 2015-06-27 07:14
Please confirm if it works or still does not work after the latest commit 0dee8a973e4217439387b02ae7abe9e8b6df584d

**Comment by pomutemu** [comment] 2016-02-03 02:02
It had trouble with `KEYTIMEOUT`
`KEYTIMEOUT=40` on my enviroment.
`export KEYTIMEOUT=1000` and Arrow keys works.
So, I think that https://github.com/zsh-users/zaw/blob/master/functions/filter-select#L710 is not really robust.

**Comment by willghatch** [comment] 2016-02-15 18:22
I use `KEYTIMEOUT=40` and it works fine for me on both zsh 5.0.7 and 5.2.  What platform are you on?  Are you doing it over ssh or something?

**Comment by termoshtt** [comment] 2017-11-22 06:24
I will close it because I cannot reproduce. If anyone reproduce it, please let me know your environment.

**Closed by termoshtt** 2017-11-22 06:24 UTC
